{
 "title": "Postgres",
 "tags": [ "image" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Big PDF",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT encode(img, 'base64') from images where name='postgresql-14-US';"
    }
   ]
  },
  {
   "title": "Image",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT encode(img, 'base64') from images where name='image-panel';"
    }
   ]
  },
  {
   "title": "Video",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT concat('data:video/mp4;base64,', encode(video, 'base64')) from videos where name='flow';"
    }
   ]
  },
  {
   "title": "Audio",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT concat('data:audio/mp3;base64,', encode(audio, 'base64')) from audios where name='call';"
    }
   ]
  }
 ]
}