version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  pdf-loader:
    build: ./postgres
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

  grafana:
    container_name: grafana
    image: grafana/grafana:9.0.0
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-image-panel
      - ./provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
