name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check for playwright
        id: playwright-check
        run: |
          echo "PLAYWRIGHT_EXISTS=$(test -f playwright.config.ts && echo true || echo false)" >> $GITHUB_OUTPUT
        working-directory: ${{ matrix.pluginDir }}

      - name: Setup playwright browser
        run: npx playwright install --with-deps chromium
        if: steps.playwright-check.outputs.PLAYWRIGHT_EXISTS == 'true'
        working-directory: ${{ matrix.pluginDir }}

      - name: Start Grafana
        run: docker-compose up -d

      - name: Run e2e tests
        run: npm run e2e

      - name: Stop Grafana
        run: docker-compose down
